insert into department (departmentname) values ("IT");
 insert into department (departmentname) values ("PRODUCTION");
 insert into department (departmentname) values ("SALES");
--  
 
 insert into _role (title, salary, departmentid) values ("Manager", 90.000, 1);
 insert into _role (title, salary, departmentid) values ("Manager", 90.000, 2);
 insert into _role (title, salary, departmentid) values ("Manager", 90.000, 3);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 1);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 2);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 3);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 1);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 2);
 insert into _role (title, salary, departmentid) values ("Supervisor", 60.000, 3);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 1);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 2);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 3);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 1);
insert into _role (title, salary, departmentid) values ("Worker", 50.000, 2);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 3);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 1);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 2);
 insert into _role (title, salary, departmentid) values ("Worker", 50.000, 3);
 insert into _role (title, salary, departmentid) values ("Intern", 35.000, 1);
 insert into _role (title, salary, departmentid) values ("Intern", 35.000, 2);
 insert into _role (title, salary, departmentid) values ("Intern", 35.000, 3);
 
  insert into employees (firstname, lastname, roleid, managerid) values ("Scarlett","Johansonn",1,null);
 insert into employees (firstname, lastname, roleid, managerid) values ("Marilyn","Monroe", 2,null);
 insert into employees (firstname, lastname, roleid, managerid) values ("Marco","Mazzoli", 3,null);
  insert into employees (firstname, lastname, roleid, managerid) values ("Bud","Spencer", 4,3);
 insert into employees (firstname, lastname, roleid, managerid) values ("Frank","Castle", 5,1);  
 insert into employees (firstname, lastname, roleid, managerid) values ("Steve","Rogers", 6,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Tony","Stark", 7,1);
 insert into employees (firstname, lastname, roleid, managerid) values ("Thor","Godofthunder", 8,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Wade","Wilson", 9,3);
 insert into employees (firstname, lastname, roleid, managerid) values ("Franco","Castiglione", 10,1);  
 insert into employees (firstname, lastname, roleid, managerid) values ("Fufos","Smith", 11,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Terence","Hill", 12,3);
 insert into employees (firstname, lastname, roleid, managerid) values ("James","Logan", 13,1);
 insert into employees (firstname, lastname, roleid, managerid) values ("Carmen","Sandiego", 14,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Rocco","Siffredi", 15,3);
 insert into employees (firstname, lastname, roleid, managerid) values ("Jack","Frost", 16,1);
 insert into employees (firstname, lastname, roleid, managerid) values ("Russell","Crow", 17,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Gino","Philips", 18,3);
 insert into employees (firstname, lastname, roleid, managerid) values ("Matt","Damon", 19,1);
 insert into employees (firstname, lastname, roleid, managerid) values ("Danny","Rand", 20,2);
 insert into employees (firstname, lastname, roleid, managerid) values ("Paolo","Noise", 21,3);